# Generated by Django 2.0.2 on 2018-04-25 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='ID аккаунта в системе 4bill')),
                ('wallet_id', models.IntegerField(verbose_name='ID кошелька в системе 4bill')),
                ('service_id', models.IntegerField(verbose_name='ID сервиса в системе 4bill')),
                ('customer_ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP-адрес пользователя')),
                ('amount', models.IntegerField(verbose_name='Сумма оплаты')),
                ('amount_currency', models.CharField(default='UAH', max_length=16, verbose_name='Валюта (формат ISO)')),
                ('description', models.TextField(blank=True, verbose_name='Описание транзакции')),
                ('status', models.CharField(max_length=32, verbose_name='Статус транзакции')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
