# Generated by Django 2.0.2 on 2018-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFor4billAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=20, help_text='Изменять можно только в том случае, если перестали работать запросы к API', verbose_name='Значение Key для 4bill API')),
            ],
            options={
                'verbose_name': 'Key для 4bill API',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(verbose_name='ID аккаунта в системе 4bill')),
                ('wallet_id', models.IntegerField(verbose_name='ID кошелька в системе 4bill')),
                ('service_id', models.IntegerField(verbose_name='ID сервиса в системе 4bill')),
                ('customer_ip_address', models.GenericIPAddressField(default='0.0.0.0', verbose_name='IP-адрес пользователя')),
                ('amount', models.IntegerField(verbose_name='Сумма оплаты')),
                ('amount_currency', models.CharField(default='UAH', max_length=16, verbose_name='Валюта (формат ISO)')),
                ('tpp_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID записи в таблице tpp БД turnes')),
                ('description', models.TextField(blank=True, verbose_name='Описание транзакции')),
                ('status', models.CharField(max_length=32, verbose_name='Статус транзакции')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен?')),
                ('provider_transaction_id', models.IntegerField(default=0, verbose_name='ID транзакции в системе 4bill')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'verbose_name': 'Payment',
            },
        ),
    ]
