# Generated by Django 2.0.2 on 2018-04-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_provider_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyFor4billAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BigIntegerField(default=20, help_text='Изменять можно только в том случае, если перестали рабоать запросы к API', verbose_name='Значение Key для 4bill API')),
            ],
            options={
                'verbose_name': 'Key для 4bill API',
            },
        ),
    ]
