# Generated by Django 2.0.2 on 2018-09-03 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_payment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPrivat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpp_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID записи в таблице tpp БД turnes')),
                ('contract_num', models.CharField(max_length=32, verbose_name='Номер договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_dt', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privat_lk_pays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
