# Generated by Django 2.0.2 on 2018-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_keyfor4billapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='tpp_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID записи в таблице tpp БД turnes'),
        ),
        migrations.AlterField(
            model_name='keyfor4billapi',
            name='key',
            field=models.BigIntegerField(default=20, help_text='Изменять можно только в том случае, если перестали работать запросы к API', verbose_name='Значение Key для 4bill API'),
        ),
    ]
