# Generated by Django 2.0.2 on 2018-05-03 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.managers
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('mobile_phone', models.CharField(max_length=30, unique=True, verbose_name='mobile phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True, validators=[users.validators.mobile_phone_number], verbose_name='Номер телефона')),
                ('two_authy', models.BooleanField(default=False, verbose_name='Двухфакторная аутентификация')),
                ('verify_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='Код подтверждения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Дополнительная информация',
                'verbose_name': 'Дополнительная информация',
            },
        ),
        migrations.CreateModel(
            name='RequestPersonalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('contract_num', models.CharField(max_length=32, verbose_name='Номер договора')),
                ('mobile_phone_number', models.CharField(max_length=32, validators=[users.validators.mobile_phone_number], verbose_name='Номер телефона')),
                ('turnes_person_id', models.CharField(blank=True, max_length=32, verbose_name='ID клиента в БД Turnes')),
            ],
            options={
                'verbose_name_plural': 'Заявки на доступ в ЛК',
                'verbose_name': 'Заявка на доступ в ЛК',
            },
        ),
    ]
