# Generated by Django 2.0.2 on 2018-05-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_two_authy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestPersonalArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('contract_num', models.CharField(max_length=32, verbose_name='Номер договора')),
                ('mobile_phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Заявка на доступ в ЛК',
                'verbose_name_plural': 'Заявки на доступ в ЛК',
            },
        ),
    ]
