# Generated by Django 2.0.2 on 2018-05-03 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180503_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpersonalarea',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
