# Generated by Django 2.0.2 on 2018-05-04 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_requestpersonalarea_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpersonalarea',
            name='user',
        ),
    ]
