# Generated by Django 2.0.2 on 2018-05-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_requestpersonalarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpersonalarea',
            name='turnes_person_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='ID клиента в БД Turnes'),
        ),
    ]
