# Generated by Django 2.0.2 on 2018-05-03 10:00

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_requestpersonalarea_turnes_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=32, unique=True, validators=[users.validators.mobile_phone_number], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='requestpersonalarea',
            name='mobile_phone_number',
            field=models.CharField(max_length=32, validators=[users.validators.mobile_phone_number], verbose_name='Номер телефона'),
        ),
    ]
