# Generated by Django 2.0.2 on 2018-05-04 06:41

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_requestpersonalarea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=30, unique=True, validators=[users.validators.mobile_phone_number], verbose_name='mobile phone'),
        ),
    ]
