# Generated by Django 2.0.2 on 2018-05-04 06:43

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180504_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpersonalarea',
            name='mobile_phone_number',
            field=models.CharField(max_length=32, unique=True, validators=[users.validators.mobile_phone_number], verbose_name='Номер телефона'),
        ),
    ]
