# Generated by Django 2.0.2 on 2018-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_turnes_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='changed_default_password',
            field=models.BooleanField(default=False, verbose_name='Стандартный пароль из sms был изменен'),
        ),
    ]
