# Generated by Django 2.0.2 on 2018-05-22 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_changed_default_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Прізвище')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name="Ім'я")),
                ('middle_name', models.CharField(blank=True, max_length=128, verbose_name='По батькові')),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('mobile_phone', models.CharField(blank=True, max_length=30, validators=[users.validators.mobile_phone_number], verbose_name='Контактний телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email адрес')),
                ('itn', models.CharField(blank=True, max_length=30, verbose_name='ІПН')),
                ('passport_code', models.CharField(blank=True, max_length=9, verbose_name='Серія та номер паспорта/Номер ID-картки')),
                ('passport_date', models.DateField(blank=True, null=True, verbose_name='Дата видачі паспорта')),
                ('passport_outdate', models.DateField(blank=True, null=True, verbose_name='Дійсний до (для ID карти)')),
                ('passport_authority', models.CharField(blank=True, max_length=128, verbose_name='Орган, що видав')),
                ('registration_country', models.TextField(blank=True, verbose_name='Країна')),
                ('registration_state', models.TextField(blank=True, verbose_name='Регіон')),
                ('registration_district', models.TextField(blank=True, verbose_name='Район')),
                ('registration_city', models.TextField(blank=True, verbose_name='Місто (СМТ, село)')),
                ('registration_street', models.TextField(blank=True, verbose_name='Вулиця (проспект, бульвар тощо)')),
                ('registration_building', models.TextField(blank=True, verbose_name='№ Будинку')),
                ('registration_flat', models.TextField(blank=True, verbose_name='№ Квартири')),
                ('registration_index', models.TextField(blank=True, verbose_name='Поштовий індекс')),
                ('residence_country', models.TextField(blank=True, verbose_name='Країна')),
                ('residence_state', models.TextField(blank=True, verbose_name='Регіон')),
                ('residence_district', models.TextField(blank=True, verbose_name='Район')),
                ('residence_city', models.TextField(blank=True, verbose_name='Місто (СМТ, село)')),
                ('residence_street', models.TextField(blank=True, verbose_name='Вулиця (проспект, бульвар тощо)')),
                ('residence_building', models.TextField(blank=True, verbose_name='№ Будинку')),
                ('residence_flat', models.TextField(blank=True, verbose_name='№ Квартири')),
                ('residence_index', models.TextField(blank=True, verbose_name='Поштовий індекс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
    ]
