# Generated by Django 2.0.2 on 2018-05-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('value', models.CharField(max_length=128, verbose_name='Значение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name_plural': 'Страны (для анкеты)',
                'verbose_name': 'Страна (для анкеты)',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='passport_code',
            field=models.CharField(blank=True, max_length=9, verbose_name='Серія та номер паспорта / Номер ID-картки'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='registration_state',
            field=models.TextField(blank=True, verbose_name='Область (Регіон)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='residence_state',
            field=models.TextField(blank=True, verbose_name='Область (Регіон)'),
        ),
    ]
