# Generated by Django 2.0.2 on 2018-05-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180524_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='bonuses',
            field=models.TextField(blank=True, verbose_name='Бонуси та премії'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bound_person_address',
            field=models.TextField(blank=True, verbose_name='Адреса фактичного проживання'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bound_person_itn',
            field=models.TextField(blank=True, verbose_name='Індивідуальний податковий номер (ІПН)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bound_person_job',
            field=models.TextField(blank=True, verbose_name='Робота (Назва компанії, Адреса, Телефон тощо)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bound_person_names',
            field=models.TextField(blank=True, verbose_name='ПІБ'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bound_person_phone',
            field=models.TextField(blank=True, verbose_name='Контактний номер телефону'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='bound_person_relationship',
            field=models.TextField(blank=True, verbose_name='Ступінь відносин'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='Фактична адреса місця праці'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='company_experience',
            field=models.TextField(blank=True, verbose_name='Стаж роботи в компанії'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='company_name',
            field=models.TextField(blank=True, verbose_name='Назва компанії'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='company_phone',
            field=models.TextField(blank=True, verbose_name='Контактний номер компанії'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='dwelling_type',
            field=models.TextField(blank=True, verbose_name='Тип житла'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='edrpou_code',
            field=models.TextField(blank=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='education',
            field=models.TextField(blank=True, verbose_name='Освіта'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='employment_type',
            field=models.TextField(blank=True, choices=[('', 'Виберіть вид'), ('individual', 'Фізична особа'), ('entrepreneur', 'Фізична особа - підприємець (ФОП)')], verbose_name='Вид зайнятості'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='has_criminal_record',
            field=models.BooleanField(default=False, verbose_name='Наявність судимості'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='labor_relations',
            field=models.TextField(blank=True, verbose_name='Трудові правовідносини'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='marital_status',
            field=models.TextField(blank=True, verbose_name='Сімейний стан'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='month_loan_payments_outgoing',
            field=models.TextField(blank=True, verbose_name='Щомісячні платежі по кредитам'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='month_outgoing',
            field=models.TextField(blank=True, verbose_name='Щомісячні витрати'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='other_income',
            field=models.TextField(blank=True, verbose_name='Інший дохід'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='other_outgoing',
            field=models.TextField(blank=True, verbose_name='Інші витрати'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='overall_experience',
            field=models.TextField(blank=True, verbose_name='Загальний трудовий стаж'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='overall_income',
            field=models.TextField(blank=True, verbose_name='Загальний дохід'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='partner_pension',
            field=models.TextField(blank=True, verbose_name='Пенсія чоловіка/дружини'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='partner_salary',
            field=models.TextField(blank=True, verbose_name='Заробітна плата чоловіка/дружини'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='pension',
            field=models.TextField(blank=True, verbose_name='Пенсія'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='position',
            field=models.TextField(blank=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='position_type',
            field=models.TextField(blank=True, verbose_name='Вид персоналу'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='salary',
            field=models.TextField(blank=True, verbose_name='Заробітна плата'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='service_type',
            field=models.TextField(blank=True, verbose_name='Сфера діяльності'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Чоловік'), ('female', 'Жінка')], max_length=10, verbose_name='Стать'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='social_benefits',
            field=models.TextField(blank=True, verbose_name='Соціальні пільги'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='vehicle_count',
            field=models.IntegerField(default=0, verbose_name='Кількість автомобілів'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='vehicle_description',
            field=models.TextField(blank=True, verbose_name='Опис авто (марка, модель тощо)'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='itn',
            field=models.CharField(max_length=10, verbose_name='Індивідуальний податковий номер (ІПН)'),
        ),
    ]
