# Generated by Django 2.0.2 on 2018-05-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180525_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ready_for_turnes',
            field=models.BooleanField(default=False, verbose_name='Анкета полностью заполнена'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='bound_person_relationship',
            field=models.TextField(blank=True, choices=[('', '')], verbose_name='Ступінь відносин'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='education',
            field=models.TextField(blank=True, choices=[('', '')], verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='labor_relations',
            field=models.TextField(blank=True, choices=[('', '')], verbose_name='Трудові правовідносини'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='marital_status',
            field=models.TextField(blank=True, choices=[('', '')], verbose_name='Сімейний стан'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='position_type',
            field=models.TextField(blank=True, choices=[('', '')], verbose_name='Вид персоналу'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='service_type',
            field=models.TextField(blank=True, choices=[('', '')], verbose_name='Сфера діяльності'),
        ),
    ]
