# Generated by Django 2.0.2 on 2018-05-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20180529_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='activity_type',
            field=models.TextField(blank=True, verbose_name='Вид діяльності (КВЕД)'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='confirmed_document',
            field=models.TextField(blank=True, verbose_name='Документ, що підтверджує державну реєстрацію'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='credit_period',
            field=models.TextField(blank=True, verbose_name='Періодичність оплати'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='credit_sum',
            field=models.TextField(blank=True, verbose_name='Сума кредиту'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='credit_term',
            field=models.TextField(blank=True, verbose_name='Термін кредиту'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='employ_count',
            field=models.TextField(blank=True, choices=[('1-2', '1-2'), ('3-5', '3-5'), ('6-10', '6-10'), ('11', 'більше 10')], verbose_name='Кількість співробітників'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='state_registration_authority',
            field=models.TextField(blank=True, verbose_name='Орган державної реєстрації'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='state_registration_date',
            field=models.TextField(blank=True, verbose_name='Дата державної реєстрації'),
        ),
    ]
