# Generated by Django 2.0.2 on 2018-05-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180530_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='bound_person_relationship',
            field=models.TextField(blank=True, verbose_name='Ступінь відносин'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='labor_relations',
            field=models.TextField(blank=True, verbose_name='Трудові правовідносини'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='marital_status',
            field=models.TextField(blank=True, verbose_name='Сімейний стан'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='position_type',
            field=models.TextField(blank=True, verbose_name='Вид персоналу'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='service_type',
            field=models.TextField(blank=True, verbose_name='Сфера діяльності'),
        ),
    ]
