# Generated by Django 2.0.2 on 2018-05-31 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20180530_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anketa', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
