# Generated by Django 2.0.2 on 2018-05-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20180531_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='vehicle_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість автомобілів'),
        ),
    ]
