# Generated by Django 2.0.2 on 2018-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20180531_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='blacklist',
            field=models.BooleanField(default=False, verbose_name='В черном списке'),
        ),
    ]
