# Generated by Django 2.0.2 on 2018-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_questionnaire_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='vehicle_count',
            field=models.IntegerField(default=0, verbose_name='Кількість автомобілів'),
        ),
    ]
