# Generated by Django 2.0.2 on 2018-08-30 11:42

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20180531_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpersonalarea',
            name='mobile_phone_number',
            field=models.CharField(max_length=32, validators=[users.validators.mobile_phone_number], verbose_name='Номер телефона'),
        ),
    ]
