# Generated by Django 2.0.2 on 2018-08-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20180830_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestpersonalarea',
            name='has_account',
            field=models.BooleanField(default=False, verbose_name='Создан аккаунт'),
        ),
    ]
