# Generated by Django 2.0.2 on 2018-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20181115_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='turnes_person_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID клиента в БД Turnes'),
        ),
    ]
