# Generated by Django 2.0.2 on 2018-11-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20181115_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='vehicle_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість автомобілів'),
        ),
    ]
