# Generated by Django 2.0.2 on 2018-12-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20181119_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='passport_authority',
            field=models.CharField(blank=True, max_length=255, verbose_name='Орган, що видав'),
        ),
    ]
