# Generated by Django 2.0.2 on 2018-06-12 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.TextField(blank=True, verbose_name='Страна')),
                ('state', models.TextField(blank=True, verbose_name='Область')),
                ('city', models.TextField(blank=True, verbose_name='Город')),
                ('street', models.TextField(blank=True, verbose_name='Улица')),
                ('type', models.TextField(blank=True, help_text='factual — адрес регистрации\nbirth – адрес рождения', verbose_name='Тп адреса')),
                ('date_modification', models.TextField(blank=True, verbose_name='Последняя дата модификации данных')),
            ],
            options={
                'verbose_name': 'Адреса (BankID)',
                'verbose_name_plural': 'Адрес (BankID)',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_id', models.TextField(blank=True, verbose_name='Идентификатор клиента')),
                ('cl_id_text', models.TextField(blank=True, verbose_name='Статический текст подтверждения выдачи информации')),
                ('last_name', models.TextField(blank=True, verbose_name='Фамилия')),
                ('first_name', models.TextField(blank=True, verbose_name='Имя')),
                ('middle_name', models.TextField(blank=True, verbose_name='Отчество')),
                ('birth_day', models.TextField(blank=True, verbose_name='Дата рождения')),
                ('inn', models.TextField(blank=True, verbose_name='Идентификационный номер налогоплательщика')),
                ('phone', models.TextField(blank=True, verbose_name='Актуальный телефон')),
                ('email', models.TextField(blank=True, verbose_name='Email')),
                ('sex', models.TextField(blank=True, help_text='(M - мужской, F - женский)', verbose_name='Пол')),
                ('resident', models.TextField(blank=True, help_text='(UA — резидент, /UA — нерезидент)', verbose_name='Определение резидентности')),
                ('signature', models.TextField(blank=True, verbose_name='Подпись SHA1')),
                ('type', models.TextField(blank=True, verbose_name='Тип')),
                ('date_modification', models.TextField(blank=True, verbose_name='Последняя дата модификации данных')),
            ],
            options={
                'verbose_name': 'Клиенты (BankID)',
                'verbose_name_plural': 'Клиент (BankID)',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.TextField(blank=True, verbose_name='Кем выдан')),
                ('number', models.TextField(blank=True, verbose_name='Номер')),
                ('series', models.TextField(blank=True, verbose_name='Серия')),
                ('issue_country_iso2', models.TextField(blank=True, verbose_name='Cтрана выдачи')),
                ('date_issue', models.TextField(blank=True, verbose_name='Когда выдан')),
                ('date_expirations', models.TextField(blank=True, verbose_name='Cрок действия')),
                ('type', models.TextField(blank=True, help_text='passport – гражданский паспорт\nzpassport – загранпаспорт\nident – удостоверение личности', verbose_name='Тип документа')),
                ('date_modification', models.TextField(blank=True, verbose_name='Последняя дата модификации данных')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='bankid.Customer')),
            ],
            options={
                'verbose_name': 'Документы (BankID)',
                'verbose_name_plural': 'Документ (BankID)',
            },
        ),
        migrations.CreateModel(
            name='ScanDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл скана')),
                ('link', models.TextField(blank=True, verbose_name='URL выкачки скана')),
                ('extension', models.TextField(blank=True, verbose_name='Тип расширения файла')),
                ('number', models.TextField(blank=True, verbose_name='Порядковый номер документа')),
                ('type', models.TextField(blank=True, help_text='passport — скан гражданского паспорта\nzpassport — скан загранпаспорта\ninn – скан идентификационного налогового номера\npersonalPhoto – фотография личности (анфас)', verbose_name='Типы сканов')),
                ('date_create', models.TextField(blank=True, verbose_name='Дата сканирования')),
                ('date_modification', models.TextField(blank=True, verbose_name='Последняя дата модификации данных')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='bankid.Customer')),
            ],
            options={
                'verbose_name': 'Сканы (BankID)',
                'verbose_name_plural': 'Скан (BankID)',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addesses', to='bankid.Customer'),
        ),
    ]
