# Generated by Django 2.0.2 on 2018-06-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankid', '0002_auto_20180612_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_expirations',
            new_name='date_expiration',
        ),
    ]
