# Generated by Django 2.0.2 on 2018-06-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankid', '0003_auto_20180612_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='edrpou',
            field=models.TextField(blank=True, verbose_name='ЕДРПОУ'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.TextField(blank=True, help_text='factual — адрес регистрации; birth – адрес рождения', verbose_name='Тип адреса'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.TextField(blank=True, help_text='passport – гражданский паспорт; zpassport – загранпаспорт; ident – удостоверение личности', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='scandocument',
            name='type',
            field=models.TextField(blank=True, help_text='passport — скан гражданского паспорта; zpassport — скан загранпаспорта; inn – скан идентификационного налогового номера\npersonalPhoto – фотография личности (анфас)', verbose_name='Типы сканов'),
        ),
    ]
