# Generated by Django 2.0.2 on 2018-06-15 07:39

import bankid.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankid', '0005_auto_20180614_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandocument',
            name='file',
            field=models.FileField(blank=True, null=True, storage=bankid.storages.ProtectedFileSystemStorage, upload_to='scans/', verbose_name='Файл скана'),
        ),
    ]
