# Generated by Django 2.0.2 on 2018-06-15 09:24

import bankid.fields
import bankid.storages
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankid', '0006_auto_20180615_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandocument',
            name='file',
            field=bankid.fields.ProtectedFileField(blank=True, null=True, storage=bankid.storages.ProtectedFileSystemStorage(), upload_to='scans/', verbose_name='Файл скана'),
        ),
    ]
