# Generated by Django 2.0.2 on 2018-05-03 12:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('name_ru', models.CharField(max_length=128, null=True, verbose_name='Название тарифа')),
                ('name_ua', models.CharField(max_length=128, null=True, verbose_name='Название тарифа')),
                ('image', models.ImageField(upload_to='credit_rate', verbose_name='Картинка')),
                ('sum_min', models.PositiveIntegerField(verbose_name='Минимальная сумма кредита')),
                ('sum_max', models.PositiveIntegerField(verbose_name='Максимальная сумма кредита')),
                ('is_insurance', models.BooleanField(default=False, verbose_name='Страховка')),
                ('term_min', models.PositiveIntegerField(verbose_name='Минимальный срок кредита')),
                ('term_max', models.PositiveIntegerField(verbose_name='Максимальный срок кредита')),
                ('term_type', models.BooleanField(default=False, help_text='Если включено, то в месяцах Если отключено, то в неделях', verbose_name='Тип срока кредита')),
                ('rate_min', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Минимальная ставка, %')),
                ('rate_max', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Максимальная ставка, %')),
                ('rate_file', models.FileField(upload_to='rates_files', verbose_name='Файл с процентами, формат .json')),
            ],
            options={
                'verbose_name_plural': 'Кредитные тарифы',
                'verbose_name': 'Кредитный тариф',
            },
        ),
        migrations.CreateModel(
            name='CreditRateUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(choices=[('cash', 'Наличка'), ('stick-man', 'Пенсионер'), ('sticker', 'Стикер')], max_length=128, verbose_name='Иконка')),
                ('credit_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.CreditRate', verbose_name='Кредитный тариф')),
            ],
            options={
                'verbose_name_plural': 'Популярные кредитные тарифы, вверху на главной',
                'verbose_name': 'Популярный кредитный тариф',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Пр. раз в месяц', max_length=128, verbose_name='Платеж')),
                ('term_ru', models.CharField(help_text='Пр. раз в месяц', max_length=128, null=True, verbose_name='Платеж')),
                ('term_ua', models.CharField(help_text='Пр. раз в месяц', max_length=128, null=True, verbose_name='Платеж')),
            ],
            options={
                'verbose_name_plural': 'Сроки платежей',
                'verbose_name': 'Платеж',
            },
        ),
        migrations.AddField(
            model_name='creditrate',
            name='payment_terms',
            field=models.ManyToManyField(to='credit.PaymentTerm', verbose_name='Сроки платежей'),
        ),
    ]
