# Generated by Django 2.0.2 on 2018-11-19 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_auto_20180503_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackFailForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.SuccessFormStatic', verbose_name='Форма успешного заказа')),
            ],
            options={
                'verbose_name_plural': 'Формы неуспешного действия',
                'verbose_name': 'Форма неуспешного действия',
            },
        ),
    ]
