# Generated by Django 2.0.2 on 2018-11-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_callbackfailform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackfailform',
            name='success',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communication.SuccessFormStatic', verbose_name='Форма успешного заказа'),
        ),
    ]
