# Generated by Django 2.0.2 on 2018-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='any_param',
            field=models.CharField(blank=True, max_length=128, verbose_name='Linkprofit any_param'),
        ),
        migrations.AddField(
            model_name='bid',
            name='wm_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Linkprofit wm_id'),
        ),
    ]
