# Generated by Django 2.0.2 on 2018-07-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20180712_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='aff_id',
            field=models.CharField(blank=True, max_length=64, verbose_name='Salesdoubler aff_id'),
        ),
        migrations.AddField(
            model_name='bid',
            name='aff_sub',
            field=models.CharField(blank=True, max_length=64, verbose_name='Salesdoubler aff_sub'),
        ),
        migrations.AddField(
            model_name='bid',
            name='v',
            field=models.CharField(blank=True, max_length=64, verbose_name='Doaffilate v'),
        ),
    ]
