# Generated by Django 2.0.2 on 2018-05-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City24Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Номер EF в системе City24')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции City24')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены заказа')),
            ],
            options={
                'verbose_name_plural': 'Транзакции City24',
                'verbose_name': 'Транзакция City24',
            },
        ),
        migrations.CreateModel(
            name='EasypayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Номер EF в системе EasyPay')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции EasyPay')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата заказа')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены заказа')),
            ],
            options={
                'verbose_name_plural': 'Транзакции EasyPay',
                'verbose_name': 'Транзакция EasyPay',
            },
        ),
        migrations.CreateModel(
            name='Tcash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа (sum)')),
                ('note', models.CharField(max_length=128, verbose_name='Примечание (note)')),
                ('type', models.CharField(max_length=32, verbose_name='Тип (in/out, type)')),
                ('service_code', models.CharField(max_length=128, verbose_name='ID платежа в системе PrivatBank')),
                ('vreme', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name_plural': 'Turnes cash (test example of tcash)',
                'verbose_name': 'Turnes cash (test example of tcredits)',
            },
        ),
        migrations.CreateModel(
            name='Tcredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.PositiveIntegerField(verbose_name='ID клиента (client_id)')),
                ('suma', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма кредита (suma)')),
                ('vnoska', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Платеж (vnoska)')),
                ('egn', models.PositiveIntegerField(verbose_name='ИНН (egn)')),
                ('contract_num', models.PositiveIntegerField(verbose_name='Номер договора (contract_num)')),
            ],
            options={
                'verbose_name_plural': 'Turnes credits (test example of tcredits)',
                'verbose_name': 'Turnes credit (test example of tcredits)',
            },
        ),
        migrations.CreateModel(
            name='Tpersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя клиента (name)')),
                ('name2', models.CharField(max_length=64, verbose_name='Отчество клиента (name2)')),
                ('name3', models.CharField(max_length=64, verbose_name='Фамилия клиента (name3)')),
                ('egn', models.PositiveIntegerField(verbose_name='ИНН (egn)')),
            ],
            options={
                'verbose_name_plural': 'Turnes persons (test example of tpersons)',
                'verbose_name': 'Turnes person (test example of tpersons)',
            },
        ),
    ]
