# Generated by Django 2.0.2 on 2018-08-13 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatbankPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128, verbose_name='ID транзакции (ПБ)')),
                ('inrazpredelenie_id', models.CharField(max_length=128, verbose_name='ID in_razpredelenie')),
                ('client_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('created_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания транзакции')),
                ('confirm_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name_plural': 'Транзакции PrivatBank',
                'verbose_name': 'Транзакция PrivatBank',
            },
        ),
    ]
