# Generated by Django 2.0.2 on 2018-08-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0003_auto_20180813_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatbankpayment',
            name='contract_num',
            field=models.CharField(default='', max_length=128, verbose_name='Номер договора'),
            preserve_default=False,
        ),
    ]
