# Generated by Django 2.0.2 on 2018-08-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0004_privatbankpayment_contract_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='easypaypayment',
            name='inrazpredelenie_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie'),
        ),
    ]
