# Generated by Django 2.0.2 on 2018-08-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0005_easypaypayment_inrazpredelenie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatbankpayment',
            name='transaction_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='ID транзакции (ПБ)'),
        ),
    ]
