# Generated by Django 2.0.2 on 2018-08-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0006_auto_20180822_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='city24payment',
            name='inrazpredelenie_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie'),
        ),
    ]
