# Generated by Django 2.0.2 on 2018-08-28 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0007_city24payment_inrazpredelenie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city24payment',
            name='save_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата сохранения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='easypaypayment',
            name='save_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата сохранения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city24payment',
            name='cancel_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='city24payment',
            name='confirmed_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
        migrations.AlterField(
            model_name='easypaypayment',
            name='cancel_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены'),
        ),
        migrations.AlterField(
            model_name='easypaypayment',
            name='confirmed_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения'),
        ),
    ]
