# Generated by Django 2.0.2 on 2018-08-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0008_auto_20180828_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='city24payment',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента'),
        ),
        migrations.AddField(
            model_name='easypaypayment',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента'),
        ),
    ]
