# Generated by Django 2.0.2 on 2018-08-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0009_auto_20180828_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city24payment',
            options={'verbose_name': "Транзакция Банк 'Фамільний'", 'verbose_name_plural': "Транзакции Банк 'Фамільний'"},
        ),
        migrations.AlterField(
            model_name='city24payment',
            name='order_id',
            field=models.BigIntegerField(verbose_name="Уникальный идентификатор транзакции Банк 'Фамільний'"),
        ),
        migrations.AlterField(
            model_name='city24payment',
            name='service_id',
            field=models.IntegerField(verbose_name="Номер EF в системе Банк 'Фамільний'"),
        ),
    ]
