# Generated by Django 2.0.2 on 2018-09-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0010_auto_20180828_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyCity24Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name="Номер EF в системе Банк 'Фамільний'")),
                ('order_id', models.BigIntegerField(verbose_name="Уникальный идентификатор транзакции Банк 'Фамільний'")),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('inrazpredelenie_id', models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': "Sky Транзакция Банк 'Фамільний'",
                'verbose_name_plural': "Sky Транзакции Банк 'Фамільний'",
            },
        ),
        migrations.CreateModel(
            name='SkyEasypayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Номер EF в системе EasyPay')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции EasyPay')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('inrazpredelenie_id', models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Sky Транзакция EasyPay',
                'verbose_name_plural': 'Sky Транзакции EasyPay',
            },
        ),
        migrations.CreateModel(
            name='SkyPrivatbankPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128, unique=True, verbose_name='ID транзакции (ПБ)')),
                ('inrazpredelenie_id', models.CharField(max_length=128, verbose_name='ID in_razpredelenie')),
                ('client_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('contract_num', models.CharField(max_length=128, verbose_name='Номер договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('created_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания транзакции')),
                ('confirm_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения транзакции')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Sky Транзакция PrivatBank',
                'verbose_name_plural': 'Sky Транзакции PrivatBank',
            },
        ),
    ]
