# Generated by Django 2.0.2 on 2018-10-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0011_skycity24payment_skyeasypaypayment_skyprivatbankpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='C24Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Номер EF в системе')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('inrazpredelenie_id', models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Транзакция City24',
                'verbose_name_plural': 'Транзакции City24',
            },
        ),
        migrations.CreateModel(
            name='SkyC24Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Номер EF в системе')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('inrazpredelenie_id', models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name': 'Sky Транзакция City24',
                'verbose_name_plural': 'Sky Транзакции City24',
            },
        ),
    ]
