# Generated by Django 2.0.2 on 2018-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0012_c24payment_skyc24payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortmoneEasypayPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.IntegerField(verbose_name='Сервисный номер EF')),
                ('order_id', models.BigIntegerField(verbose_name='Уникальный идентификатор транзакции')),
                ('account', models.CharField(max_length=128, verbose_name='Идентификатор пользователя (№ договора)')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('inrazpredelenie_id', models.CharField(blank=True, max_length=128, verbose_name='ID in_razpredelenie')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден?')),
                ('confirmed_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменен?')),
                ('cancel_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name_plural': 'Транзакции Portmone (тип Easypay)',
                'verbose_name': 'Транзакция Portmone (тип Easypay)',
            },
        ),
        migrations.CreateModel(
            name='PortmonePrivatPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=128, unique=True, verbose_name='ID транзакции (ПБ)')),
                ('inrazpredelenie_id', models.CharField(max_length=128, verbose_name='ID in_razpredelenie')),
                ('client_name', models.CharField(max_length=255, verbose_name='ФИО клиента')),
                ('contract_num', models.CharField(max_length=128, verbose_name='Номер договора')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cумма платежа')),
                ('created_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата создания транзакции')),
                ('confirm_dt', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения транзакции')),
                ('save_dt', models.DateTimeField(auto_now_add=True, verbose_name='Дата сохранения')),
            ],
            options={
                'verbose_name_plural': 'Транзакции Portmone (тип Privat)',
                'verbose_name': 'Транзакция Portmone (тип Privat)',
            },
        ),
    ]
