# Generated by Django 2.0.2 on 2018-10-30 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0013_portmoneeasypaypayment_portmoneprivatpayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='c24payment',
            options={'verbose_name': 'Транзакция EF (Тип City24)', 'verbose_name_plural': 'Транзакции EF (Тип City24)'},
        ),
        migrations.AlterModelOptions(
            name='city24payment',
            options={'verbose_name': 'Транзакция EF (Тип Банк Фамільний)', 'verbose_name_plural': 'Транзакции EF (Тип Банк Фамільний)'},
        ),
        migrations.AlterModelOptions(
            name='easypaypayment',
            options={'verbose_name': 'Транзакция EF (тип EasyPay)', 'verbose_name_plural': 'Транзакции EF (тип EasyPay)'},
        ),
        migrations.AlterModelOptions(
            name='privatbankpayment',
            options={'verbose_name': 'Транзакция EF (тип PrivatBank)', 'verbose_name_plural': 'Транзакции EF (тип PrivatBank)'},
        ),
        migrations.AlterModelOptions(
            name='skyc24payment',
            options={'verbose_name': 'Транзакция Sky (Тип City24)', 'verbose_name_plural': 'Транзакции Sky (Тип City24)'},
        ),
        migrations.AlterModelOptions(
            name='skycity24payment',
            options={'verbose_name': 'Транзакция Sky (Тип Банк Фамільний)', 'verbose_name_plural': 'Транзакции Sky (Тип Банк Фамільний)'},
        ),
        migrations.AlterModelOptions(
            name='skyeasypaypayment',
            options={'verbose_name': 'Транзакция Sky (Тип EasyPay)', 'verbose_name_plural': 'Транзакции Sky (Тип EasyPay)'},
        ),
        migrations.AlterModelOptions(
            name='skyprivatbankpayment',
            options={'verbose_name': 'Транзакция Sky (Тип PrivatBank)', 'verbose_name_plural': 'Транзакции Sky (Тип PrivatBank)'},
        ),
    ]
