# Generated by Django 2.0.2 on 2018-10-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0014_auto_20181030_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portmoneeasypaypayment',
            options={'verbose_name': 'Транзакция Sky (тип Portmone-Easypay)', 'verbose_name_plural': 'Транзакции Sky (тип Portmone-Easypay)'},
        ),
        migrations.AlterModelOptions(
            name='portmoneprivatpayment',
            options={'verbose_name': 'Транзакция Sky (тип Portmone-Privat)', 'verbose_name_plural': 'Транзакции Sky (тип Portmone-Privat)'},
        ),
    ]
