# Generated by Django 2.0.2 on 2019-01-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateways', '0015_auto_20181030_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c24payment',
            name='service_id',
            field=models.IntegerField(default=25, verbose_name='Номер EF в системе'),
        ),
        migrations.AlterField(
            model_name='skyc24payment',
            name='service_id',
            field=models.IntegerField(default=25, verbose_name='Номер EF в системе'),
        ),
    ]
