# Generated by Django 2.0.2 on 2018-05-03 12:33

from django.db import migrations, models
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=128, null=True, verbose_name='Город')),
                ('city_ru', models.CharField(max_length=128, null=True, verbose_name='Город')),
                ('city_ua', models.CharField(max_length=128, null=True, verbose_name='Город')),
                ('address', django_google_maps.fields.AddressField(max_length=128, verbose_name='Адрес [ru]')),
                ('address_ua', models.CharField(max_length=255, null=True, verbose_name='Адрес [ua]')),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100, null=True)),
                ('schedule', models.CharField(max_length=128, verbose_name='Режим работы')),
                ('schedule_ru', models.CharField(max_length=128, null=True, verbose_name='Режим работы')),
                ('schedule_ua', models.CharField(max_length=128, null=True, verbose_name='Режим работы')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=64, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name_plural': 'Отделения',
                'verbose_name': 'Отделение',
            },
        ),
    ]
